name: 'dbt_nothwind_mesh_foundational'
version: '1.0.0'
config-version: 2

dbt-cloud: 
  project-id: 448668
  defer-env-id: 447525

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_nothwind_mesh_foundational:

    staging:
      +materialized: view
      +schema: stg
      +access: public
      erp:
        +tags: erp
